/* Copyright 2015 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/***************************************************************************
 * A shader which an user can add in run-time.
 ***************************************************************************/

#ifndef SHADER_H_
#define SHADER_H_

#include <map>
#include <memory>
#include <string>
#include <mutex>
#include <vector>
#include <objects/mesh.h>

#include "glm/glm.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "objects/uniform_block.h"

namespace gvr {
class Mesh;

/**
 * Contains information about the vertex attributes, textures and
 * uniforms used by the shader source and the sources for the
 * vertex and fragment shaders.
 *
 * Shaders are only created by the ShaderManager when addShader is called.
 */
class Shader
{
public:
    static const bool LOG_SHADER;

/*
 * Creates a native shader description.
 * The actual GL program is not made until the first call to render()
 * @param id                ShaderManager ID for the shader
 * @param signature         Unique signature string
 * @param uniformDescriptor String giving the names and types of shader material uniforms
 *                          This does NOT include uniforms used by light sources
 * @param textureDescriptor String giving the names and types of texture samplers
 * @param vertexDescriptor  String giving the names and types of vertex attributes
 * @param vertexShader      String with GLSL source for vertex shader
 * @param fragmentShader    String with GLSL source for fragment shader
 * @see ShaderManager::addShader
 */
    Shader(int id, const std::string& signature,
            const std::string& uniformDescriptor,
            const std::string& textureDescriptor,
            const std::string& vertexDescriptor,
            const std::string& vertexShader,
            const std::string& fragmentShader);
    virtual ~Shader() { };

    /*
     * Returns the unique signature for this shader (provided
     * to ShaderManager::addShader when this Shader was created).
     */
    const std::string& signature() const { return signature_; }

    /*
     * Returns the ShaderManager ID (generated by addShader)
     */
    int getShaderID() const { return id_; }

    /*
     *  returns the vertex attributes descriptor
     */
    DataDescriptor& getVertexDescriptor()
    {
        return mVertexDesc;
    }
    /*
    *  returns the string containing the texture descriptor
    */
    const std::string& getTextureDescriptor()
    {
        return mTextures;
    }
    /*
     *  returns the uniform descriptor
     */
    DataDescriptor& getUniformDescriptor()
    {
        return mUniformDesc;
    }

    bool isTransformUboPresent(){
        return transformUboPresent;
    }
    bool isShaderDirty(){
        return  shaderDirty;
    }
    void setShaderDirty(bool flag){
        shaderDirty = flag;
    }
    virtual bool useShader() = 0;
    static int calcSize(std::string type);

private:
    Shader(const Shader& shader);
    Shader(Shader&& shader);
    Shader& operator=(const Shader& shader);
    Shader& operator=(Shader&& shader);

protected:
    std::string signature_;
    std::string vertexShader_;
    std::string fragmentShader_;
    DataDescriptor mUniformDesc;
    std::string mTextures;
    DataDescriptor mVertexDesc;
    int id_;
    bool shaderDirty = true;
    bool transformUboPresent = true;
};

}
#endif
